name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Arbitration Test
        run: docker build . -t cartesi/arbitration-test:latest -f Dockerfile.test
      
      - name: Push Arbitration Test to Docker Hub
        run: docker push cartesi/arbitration-test:latest
