name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
        ganache:
            image: trufflesuite/ganache-cli
            ports:
                - 8545:8545
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
            python-version: '12.x'
      - run: npm install -g --unsafe-perm=true --allow-root truffle
      - run: npm install

      - uses: actions/setup-python@v1
        with:
            python-version: '3.x'
      - run: pip3 install -r requirements.txt
      
      - run: ./prepare_python_tests.sh
      - run: ./run_python_tests.sh
